<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\GOtica.Communication\GOtica.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\GOtica.Exceptions\GOtica.Exceptions.csproj" />
    <ProjectReference Include="..\GOtica.Domain\GOtica.Domain.csproj" />
  </ItemGroup>

</Project>
