//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOtica.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOtica.Exceptions.Resources.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail is already registered on the platform..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail entered is not valid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail and/or password..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Log in again to continue..
        /// </summary>
        public static string EXPIRED_SESSION {
            get {
                return ResourceManager.GetString("EXPIRED_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid. It must be at least 6 characters long..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid session could not be found. Log in to access this resource..
        /// </summary>
        public static string INVALID_SESSION {
            get {
                return ResourceManager.GetString("INVALID_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new owner does not belong to this optical store..
        /// </summary>
        public static string NEW_OWNER_DOES_NOT_BELONG_OPTICAL {
            get {
                return ResourceManager.GetString("NEW_OWNER_DOES_NOT_BELONG_OPTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords do not match..
        /// </summary>
        public static string NEW_PASSWORDS_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("NEW_PASSWORDS_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This optical store is already registered.
        /// </summary>
        public static string OPTICAL_STORE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("OPTICAL_STORE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical store not found..
        /// </summary>
        public static string OPTICAL_STORE_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPTICAL_STORE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered does not match the current password..
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_ONE {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already has a pending invitation for this optical store..
        /// </summary>
        public static string PENDING_INVITE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("PENDING_INVITE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number cannot be empty..
        /// </summary>
        public static string PHONE_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must start with +351 and contain exactly 9 digits..
        /// </summary>
        public static string PHONE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role must be &apos;manager&apos; or &apos;salesperson&apos;..
        /// </summary>
        public static string ROLE_INVALID {
            get {
                return ResourceManager.GetString("ROLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number cannot be empty.
        /// </summary>
        public static string TAX_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("TAX_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already a member of the optical store..
        /// </summary>
        public static string USER_ALREADY_MEMBER_OF_OS {
            get {
                return ResourceManager.GetString("USER_ALREADY_MEMBER_OF_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already owner.
        /// </summary>
        public static string USER_ALREADY_OWNER {
            get {
                return ResourceManager.GetString("USER_ALREADY_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not belong to this optical store..
        /// </summary>
        public static string USER_DOES_NOT_BELONG_OPTICAL {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_BELONG_OPTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner of the optical store can transfer ownership..
        /// </summary>
        public static string USER_IS_NOT_OWNER {
            get {
                return ResourceManager.GetString("USER_IS_NOT_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user cannot deactivate the account while they are an owner of an optical store..
        /// </summary>
        public static string USER_IS_STILL_OWNER {
            get {
                return ResourceManager.GetString("USER_IS_STILL_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid invite was not found..
        /// </summary>
        public static string VALID_INVITE_NOT_FOUND {
            get {
                return ResourceManager.GetString("VALID_INVITE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
